version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16
    container_name: ad-alchemy-db
    environment:
      POSTGRES_DB: ad_alchemy_db
      POSTGRES_USER: ad_alchemy_user
      POSTGRES_PASSWORD: ad_alchemy_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ad_alchemy_user -d ad_alchemy_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Redis (for caching and session management)
  redis:
    image: redis:7-alpine
    container_name: ad-alchemy-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ad-alchemy-backend
    environment:
      - ENVIRONMENT=development
      - DEBUG=True
      - POSTGRES_DATABASE_URL=postgresql+asyncpg://ad_alchemy_user:ad_alchemy_password@postgres:5432/ad_alchemy_db
      - REDIS_URL=redis://redis:6379/0
      - CORS_ORIGINS=["http://localhost:3000"]
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/__pycache__
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Next.js Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ad-alchemy-frontend
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  redis_data:

networks:
  default:
    name: ad-alchemy-network